In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.3.0'

### Tensor

**Tensor** là yếu tố chính để ta thực hiện tính toán trong TF. Nói chung tensor là một mảng nhiều chiều với kiểu dữ liệu xác định. Nghĩa là mỗi thành phần của tensor có cùng kiểu dữ liệu (tf.int32, tf.float32, ...) và luôn như vậy trong quá trình tính toán. Có nhiều cách để tạo ra tensor, nhưng hai cách chủ yếu là constants và variables.

**Constants**

Sử dụng các phương thức: tf.ones(), tf.zeros(), tr.eye(), ...

In [5]:
a = tf.ones(shape=(2,3), dtype=tf.int32)
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [6]:
a = tf.zeros(shape=(2,3), dtype=tf.int32)
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [10]:
a = tf.eye(3, dtype=tf.int32)
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)>

Tạo bằng cách truyền dữ liệu thông qua kiểu dữ liệu Python/numpy  [More info](https://www.tensorflow.org/api_docs/python/tf/constant)

In [11]:
b = tf.constant([[1, 2, 3], [4, 5, 6]])
print("b =",b);

npvar = np.array(["hello", "world"])
c = tf.constant(npvar)
print("\nc =", c)

d = tf.constant(10.0, shape=[2,5])
print("\nd =", d)

b = tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

c = tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)

d = tf.Tensor(
[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]], shape=(2, 5), dtype=float32)


Tạo các biến ngẫu nhiên

In [12]:
e = tf.random.normal(shape=[2, 3], mean=0.0, stddev=1.0)
print("e =", e)

f = tf.random.uniform( shape=[2,3], minval=0,maxval=10,dtype=tf.int32)
print("\nf =", f)

e = tf.Tensor(
[[ 1.0624503  -0.5085749   0.21090114]
 [ 0.30452174  1.9169184   0.54680943]], shape=(2, 3), dtype=float32)

f = tf.Tensor(
[[9 6 9]
 [4 3 9]], shape=(2, 3), dtype=int32)


### Variables

Cách duy nhất để tạo variable là dùng lớp *tf.variable(<required-init-name>, name=<optional-name>). TF sử dụng biến gán ban đầu để khởi tạo shape và kiểu dữ liệu (dtype), hai thuộc tính này không được thay đổi trong quá trình tính toán. 

In [14]:
w = tf.Variable(20., name="my_var1")
print('w =', w)

initializer = tf.initializers.GlorotUniform()
x = tf.Variable(initializer(shape=(2, 5)), name="my_var2")
print('\nx =', x)

y = tf.Variable(tf.zeros([5]), name='my_var3')
print('\ny =', y)

w = <tf.Variable 'my_var1:0' shape=() dtype=float32, numpy=20.0>

x = <tf.Variable 'my_var2:0' shape=(2, 5) dtype=float32, numpy=
array([[-0.37487346,  0.49646413, -0.77523494, -0.400365  ,  0.3821311 ],
       [ 0.11485541,  0.10919476, -0.02570367,  0.47769165, -0.21898031]],
      dtype=float32)>

y = <tf.Variable 'my_var3:0' shape=(5,) dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>


In [21]:
# API của Variable hầu hết giống với tf.Tensor. Chúng ta có thể xem như là 1 tf.Tensor

v = w + 1.  # v là một tf.Tensor và là kết quả của phép tính của variable w
            # tf.Variable tự động ép kiểu (auto converted) sang tf.Tensor

print("v =", v)
print(f"v's type = {type(v)}")
print(f"w's type = {type(w)}")

v = tf.Tensor(43.0, shape=(), dtype=float32)
v's type = <class 'tensorflow.python.framework.ops.EagerTensor'>
w's type = <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


Để thay đổi giá trị hiện tại của variable ta có thể dùng hai phương thức assign (=) và assign_add (+=).

In [22]:
print('w =', w)
w.assign(v)
print('w =', w)
w.assign_add(v)
print('w =', w)

w = <tf.Variable 'my_var1:0' shape=() dtype=float32, numpy=42.0>
w = <tf.Variable 'my_var1:0' shape=() dtype=float32, numpy=43.0>
w = <tf.Variable 'my_var1:0' shape=() dtype=float32, numpy=86.0>


### Rank, Shape, and Type Conversion¶

In [26]:

print(f"a = \n{a}")
print("a.dtype =", a.dtype)
print("a.shape =", a.shape)
print("a.rank =", len(a.shape))
# or...
print("\na.shape =", tf.shape(a))
print("a.rank =", tf.rank(a)) 

print("\ne (dtype = float - thực) =", e)
e_int = tf.cast(e, tf.int32) # Chuyển sang kiểu int
print("\ne (dtype = int - nguyên) =", e_int)

# Chuyển kiểu Tensor sang numpy
e_np = e_int.numpy()
print(f"\ntype(e_np) = {type(e_np)}")
e_np

a = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
a.dtype = <dtype: 'int32'>
a.shape = (3, 3)
a.rank = 2

a.shape = tf.Tensor([3 3], shape=(2,), dtype=int32)
a.rank = tf.Tensor(2, shape=(), dtype=int32)

e (dtype = float - thực) = tf.Tensor(
[[ 1.0624503  -0.5085749   0.21090114]
 [ 0.30452174  1.9169184   0.54680943]], shape=(2, 3), dtype=float32)

e (dtype = int - nguyên) = tf.Tensor(
[[1 0 0]
 [0 1 0]], shape=(2, 3), dtype=int32)

type(e_np) = <class 'numpy.ndarray'>


array([[1, 0, 0],
       [0, 1, 0]], dtype=int32)

### Tensor manipulation
#### Element-Wise Operations

In [27]:
t1 = tf.constant([[0, 0, 0], [0, 1, 1], [0, 1, 1]])
t2 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('t1 + t2 =', t1 + t2)
print('t2 - t1 =', t2 - t1)
print('t1 * t2 =', t1 * t2)
print('t1 / t2 =', t1 / t2)

t1 + t2 = tf.Tensor(
[[ 1  2  3]
 [ 4  6  7]
 [ 7  9 10]], shape=(3, 3), dtype=int32)
t2 - t1 = tf.Tensor(
[[1 2 3]
 [4 4 5]
 [7 7 8]], shape=(3, 3), dtype=int32)
t1 * t2 = tf.Tensor(
[[0 0 0]
 [0 5 6]
 [0 8 9]], shape=(3, 3), dtype=int32)
t1 / t2 = tf.Tensor(
[[0.         0.         0.        ]
 [0.         0.2        0.16666667]
 [0.         0.125      0.11111111]], shape=(3, 3), dtype=float64)


Broadcasting xảy ra trong các phép toán giữa khác tensor có shape khác nhau. Về cơ bản, TF sẽ "broadcasts" tensor nhỏ hơn trên ma trận lớn hơn để chúng tương thích với nhau. Có thể xem broadcasting giống như việc lặp đi lặp lại các giá trị tensor mà không cần sao chép chúng. 
<td> <img src="https://www.tutorialspoint.com/numpy/images/array.jpg" alt="Drawing" style="width: 500px;"/> </td>

[Nguồn](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)

In [28]:
t1 = tf.constant([1, 2, 3, 4])
print("t1 + 100 =", t1 + 100)

# (m, n) + (1, n)
t1 = tf.constant([[1, 2, 3], 
                  [4, 5, 6]])
t2 = tf.constant([[100, 200, 300]])
print(f"\nt1.shape = {t1.shape}, t2.shape = {t2.shape}")
print("t1 + t2 =", t1 + t2)

# (m, n) + (n, 1)
t1 = tf.constant([[1, 2, 3], 
                  [4, 5, 6]])
t2 = tf.constant([[100], 
                  [200]])
print(f"\nt1.shape = {t1.shape}, t2.shape = {t2.shape}")
print("t1 + t2 =", t1 + t2)

# (1, n) + (m, 1)
t1 = tf.constant([[1, 2, 3]])
t2 = tf.constant([[100], 
                  [200]])
print(f"\nt1.shape = {t1.shape}, t2.shape = {t2.shape}")
print("t1 + t2 =", t1 + t2)

t1 + 100 = tf.Tensor([101 102 103 104], shape=(4,), dtype=int32)

t1.shape = (2, 3), t2.shape = (1, 3)
t1 + t2 = tf.Tensor(
[[101 202 303]
 [104 205 306]], shape=(2, 3), dtype=int32)

t1.shape = (2, 3), t2.shape = (2, 1)
t1 + t2 = tf.Tensor(
[[101 102 103]
 [204 205 206]], shape=(2, 3), dtype=int32)

t1.shape = (1, 3), t2.shape = (2, 1)
t1 + t2 = tf.Tensor(
[[101 102 103]
 [201 202 203]], shape=(2, 3), dtype=int32)


#### Matrix Multiplication

In [29]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.constant([[10, 20], 
                  [30, 40],
                  [50, 60]])
print("tf.matmul(t1, t2) =", tf.matmul(t1, t2))

tf.matmul(t1, t2) = tf.Tensor(
[[220 280]
 [490 640]], shape=(2, 2), dtype=int32)


#### Transposing

In [30]:
# tf.transpose(t, perm) hoán đổi chiều theo tham số perm
t1 = tf.constant([[1, 2, 3], [4, 5, 6]]) # (2,3) -> (3, 2)
print("tf.transpose(t1, [1, 0]) =", tf.transpose(t1, perm=[1, 0])) 

t1 = tf.ones(shape=(2, 5, 13))
t1_t = tf.transpose(t1, perm=[0, 2, 1])
print(f"\nt1_t.shape = {t1_t.shape}")

# Hoán đổi nhiều hơn hai chiều cùng một lúc
t1 = tf.ones(shape=(2, 5, 13))
t1_t = tf.transpose(t1, perm=[2, 0, 1])
print(f"\nt1_t.shape = {t1_t.shape}")

tf.transpose(t1, [1, 0]) = tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)

t1_t.shape = (2, 13, 5)

t1_t.shape = (13, 2, 5)


**Reshape** Tạo một tensor mới có cùng giá trị với tensor đã tồn tại nhưng khác shape. Yêu cầu hai tensor phải bằng nhua về kích thứơc (size)

In [32]:
t = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9]) # [9]
print(f"t_new = tf.reshape(t, [3, 3]); t_new => \n {tf.reshape(t, [3, 3])}")

t = tf.constant([[[1, 1], [2, 2]],
                [[3, 3], [4, 4]]]) # [2, 2, 2]
print(f"\nt_new = tf.reshape(t, [2, 4]); t_new => \n {tf.reshape(t, [2, 4])}")

# -1 được sử dụng để tự động tính shape
t = tf.constant([[[1, 1, 1],
                 [2, 2, 2]],
                [[3, 3, 3],
                 [4, 4, 4]],
                [[5, 5, 5],
                 [6, 6, 6]]]) # [3, 2, 3]

# -1 => 18
print(f"\nt_new = tf.reshape(t, [-1]); t_new => \n {tf.reshape(t, [-1])}")
# -1 => 9
print(f"\nt_new = tf.reshape(t, [2, -1]); t_new => \n {tf.reshape(t, [2, -1])}")
# -1 => 2
print(f"\nt_new = tf.reshape(t, [-1, 9]); t_new => \n {tf.reshape(t, [-1, 9])}")
# -1 => 3
print(f"\nt_new = tf.reshape(t, [2, -1, 3]); t_new => \n {tf.reshape(t, [2, -1, 3])}")

# Chuyển một giá trị vô hướng bằng cáchsử dụng []
t = tf.constant([5])
print(f"\nt_new = tf.reshape(t, []); t_new => \n {tf.reshape(t, [])}")

t_new = tf.reshape(t, [3, 3]); t_new => 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

t_new = tf.reshape(t, [2, 4]); t_new => 
 [[1 1 2 2]
 [3 3 4 4]]

t_new = tf.reshape(t, [-1]); t_new => 
 [1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6]

t_new = tf.reshape(t, [2, -1]); t_new => 
 [[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]

t_new = tf.reshape(t, [-1, 9]); t_new => 
 [[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]

t_new = tf.reshape(t, [2, -1, 3]); t_new => 
 [[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]

t_new = tf.reshape(t, []); t_new => 
 5


#### Combining Tensors

In [33]:

t1 = tf.constant([[1, 1, 1], [1, 1, 1]]) # [2, 3]
t2 = tf.constant([[2, 2, 2], [2, 2, 2]]) # [2, 3]
t3 = tf.constant([[3, 3, 3], [3, 3, 3]]) # [2, 3]

print(f"tf.concat([t1, t2, t3], axis=0) = \n{tf.concat([t1, t2, t3], axis=0)}") # [6, 3]
print(f"\ntf.concat([t1, t2, t3], axis=1) = \n{tf.concat([t1, t2, t3], axis=1)}") # [2, 9]

tf.concat([t1, t2, t3], axis=0) = 
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]
 [3 3 3]
 [3 3 3]]

tf.concat([t1, t2, t3], axis=1) = 
[[1 1 1 2 2 2 3 3 3]
 [1 1 1 2 2 2 3 3 3]]


In [34]:
t1 = tf.constant([1, 1, 1, 1])
t2 = tf.constant([2, 2, 2, 2])
t3 = tf.constant([3, 3, 3, 3])

print(f"tf.stack([t1, t2, t3], axis=0) = \n{tf.stack([t1, t2, t3], axis=0)}")
print(f"\ntf.stack([t1, t2, t3], axis=1) = \n{tf.stack([t1, t2, t3], axis=1)}")

tf.stack([t1, t2, t3], axis=0) = 
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]

tf.stack([t1, t2, t3], axis=1) = 
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


#### Slicing and Indexing

In [37]:
t = tf.random.uniform(shape=[4, 5, 6, 7], maxval=10, dtype=tf.int32)

# giống như Python lists và Numpy arrays
t1 = t[1:3, 0, 3:, -2:-6:-1]
print("t1 =", t1)

# giống t[0, 0, :, :]
t2 = t[0, :, :, 0]
print("\nt2 =", t2)

t1 = tf.Tensor(
[[[7 7 9 9]
  [0 0 3 3]
  [3 0 7 3]]

 [[9 3 1 9]
  [8 7 0 7]
  [0 6 1 6]]], shape=(2, 3, 4), dtype=int32)

t2 = tf.Tensor(
[[9 7 2 1 7 8]
 [7 6 9 6 9 3]
 [8 4 6 6 9 9]
 [7 3 3 2 9 8]
 [0 0 9 7 1 9]], shape=(5, 6), dtype=int32)


#### Reducing

In [38]:
t = tf.constant([[1, 2, 3, 4], 
                 [1, 2, 3, 4]])

# Tổng tất cả các phần tử
print("tf.reduce_sum(t) =", tf.math.reduce_sum(t))

# Tổng cột
print("tf.reduce_sum(t, axis=0) =", tf.math.reduce_sum(t, axis=0))

# Tổng hàng
print("tf.reduce_sum(t, axis=1) =", tf.math.reduce_sum(t, axis=1))

t1 = tf.random.uniform(shape=[3, 4], maxval=10, dtype=tf.int32)
print("\nt1 =",t1)
print("tf.reduce_min(t1) =", tf.math.reduce_min(t1))
print("tf.reduce_max(t1) =", tf.math.reduce_max(t1))
print("tf.reduce_mean(t1) =", tf.math.reduce_mean(t1))

tf.reduce_sum(t) = tf.Tensor(20, shape=(), dtype=int32)
tf.reduce_sum(t, axis=0) = tf.Tensor([2 4 6 8], shape=(4,), dtype=int32)
tf.reduce_sum(t, axis=1) = tf.Tensor([10 10], shape=(2,), dtype=int32)

t1 = tf.Tensor(
[[8 2 3 6]
 [2 4 9 4]
 [7 1 8 1]], shape=(3, 4), dtype=int32)
tf.reduce_min(t1) = tf.Tensor(1, shape=(), dtype=int32)
tf.reduce_max(t1) = tf.Tensor(9, shape=(), dtype=int32)
tf.reduce_mean(t1) = tf.Tensor(4, shape=(), dtype=int32)
