## Tensorflow 

**Tensorlfow** là một thư viện học máy được phát hành bởi Google
* Được sử dụng tốt cho các mô hình học sâu
* Được sử dụng cho nghiên cứu và xây dựng các sản phẩm

<td> <img src="https://lh3.google.com/u/0/d/1iCyyRlIN1cb8zExGpQGXCoRefI1pCvzF=w1329-h588-iv1" alt="Drawing" style="width: 500px;"/> </td>

#### Tensorflow Architecture 
1. **Data pre-processing**: Thu thập các dữ liệu phi cấu trúc, tiến hành tiền xử lí thành các dữ liệu có cấu trúc và có giá trị giới hạn nhằm chuẩn bị quá trình huấn luyện.
2. **Model building**: Xây dựng mô hình
3. **Train and estimate the model**: Sử dụng dữ liệu để huấn luyện mô hình. Huấn luyện qua các epoch nhằm tăng độ chính xác và giảm loss. Tiến hành kiểm thử với dữ liệu không có nhãn.

#### Core Concepts 
Tensorflow gồm hai phần chính:

* **Library**: Định nghĩa computational graphs 
* **Runtime**: Tiến hành thực thi (executing) các graphs trên các nền tảng phần cứng khác nhau.
<td> <img src="https://miro.medium.com/max/700/0*JLCdd59SMZ6XWdm2" alt="Drawing" style="width: 500px;"/> </td>

Khi chúng ta xây dựng các thuật toán học máy với TF, thì chúng ta sẽ xây dựng kiến trúc mô hình, sau đó sẽ được dịch (translate) vào TF computational graphs và sẽ chuyển đến **Runtime**. Sau đó thì **Runtime** sẽ lo phần còn lại. Chíu chíu.

### Computational Graph 

**Khái niệm**: Trong TF, các thuật toán học máy được biểu diễn như một computational graphs. Một CP là một đồ thị có hướng mà ở đó mỗi nốt (node) biểu diễn một phép tính (operation), trong khi đó mỗi cạnh (edge) thì biểu diễn dữ liệu (tensor) giữa các nốt. 

Một vài khái niệm liên quan đến CP.
* **Tensors**: Một tensor biểu diễn một mảng nhiều chiều (multidemensional arrays). Tensors thường sẽ có shape và data type, ko có giá trị thực tế. 
* **Operations**: Có thể có không hoặc nhiều đầu vào và có thể tạo ra không hoặc nhiều đầu ra. Như vậy một operation có thể là một phường trình toán học, biến, hằng số hoặc một luồng điều khiển (control flow directive).
* **Variables**: Tất cả các tham số có thể huấn luyện (trainable parameters) của mô hình học máy là *tf.Variables*. Một biến có thể được định nghĩa bởi tên (name), kiểu (type), shape ...

Từ TF được ghép bởi "Tensor" + "Flow" nghĩa là tensor (data) flow thông quan CP

Khi định nghĩa một graph, chúng ta sẽ sử dụng hàm *tf.Graph*. Tại thời điểm thực thi, chúng ta sử dụng TF runtime để thực thi tính toán.

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.3.0'

In [21]:
# Ví dụ về graph 
a = tf.constant(1.0) # nó là 1 op và sẽ được thêm vào 1 nốt vào tf.Graphs mặc định
b = tf.constant(1.0) 
c = tf.add(a, b)
print(c)

tf.Tensor(2.0, shape=(), dtype=float32)


<td> <img src="https://miro.medium.com/max/700/0*r6fTd-2PZf2YdKSA" alt="Drawing" style="width: 70%; display: block; margin: 0, auto"/> </td>




### Variables

**Variable**: Các biến được tạo và theo dõi thông qua lớp *tf.Variable*. Một *tf.Variable* đại diện cho một tensor có giá trị có thể thay đổi bằng cách chạy các hoạt động trên nó. Các hoạt động cụ thể cho phép bạn đọc và sửa đổi các giá trị của tensor này. Các thư viện cấp cao hơn như *tf.keras* sử dụng *tf.Variable* để lưu trữ các tham số của mô hình.

Để tạo một biến, hãy cung cấp một giá trị ban đầu. *tf.Variable* sẽ có cùng dtype với giá trị khởi tạo.

In [24]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)

# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
complex_variable = tf.Variable([5 + 4j, 6 + 1j])

Một biến trông và hoạt động giống như tensor, và trên thực tế, biến là một cấu trúc dữ liệu được hỗ trợ bởi *tf.Tensor* . Giống như tensors, chúng có một *dtype* và một *shape*, và có thể được chuyển sang NumPy.

In [25]:
print("A variable:", my_variable)
print("\nViewed as a tensor:", tf.convert_to_tensor(my_variable))
print("\nIndex of highest value:", tf.argmax(my_variable))

# This creates a new tensor; it does not reshape the variable.
print("\nCopying and reshaping: ", tf.reshape(my_variable, ([1,4])))

A variable: <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

Index of highest value: tf.Tensor([1 1], shape=(2,), dtype=int64)

Copying and reshaping:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


Nếu chúng ta sử dụng biến như một tensor trong operations, chúng ta thường hoạt động trên backing tensor (cái này dịch tensor nền dc ko nhỉ?).

Khi tạo một biến mới từ một biến đã tồn tại thì sẽ nhân đôi tensor vì chúng không dùng chung bộ nhớ. 

In [28]:
a = tf.Variable([2.0, 3.0])
# Create b based on the value of a
b = tf.Variable(a)
a.assign([5, 6])

# a and b are different
print(a.numpy())
print(b.numpy())

# There are other versions of assign
print(a.assign_add([2,3]).numpy())  # [7. 9.]
print(a.assign_sub([7,9]).numpy())  # [0. 0.]

[5. 6.]
[2. 3.]
[7. 9.]
[0. 0.]


#### Một số bài viết khá hay: 
https://www.facebook.com/notes/forum-deep-learning-v%C3%A0-%E1%BB%A9ng-d%E1%BB%A5ng/t%C3%ACm-hi%E1%BB%83u-tensor-v%C3%A0-m%E1%BB%99t-s%E1%BB%91-tensor-data-trong-deep-learning/1625331727576436/